### ISSUE TITLE
download arcface_checkpoint.tar wrong

### ISSUE THREAD

**Issue by yja1** [neuralchen/SimSwap#10]
![1](https://user-images.githubusercontent.com/24217235/122393454-7b4c0600-cfa7-11eb-9150-5b4814e59f89.png)

**Comment by woctezuma** [comment]
#9

**Comment by P-Light** [comment]
Working well with below conda env:

```yaml
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pytorch=1.5
  - torchvision=0.6.1
  - numpy=1.20.2
  - opencv=4.5.0
  - pillow=8.2.0
  - gdown=3.13.0
```

checkpoint downloaded from GDrive, cuda=10.2
