### ISSUE TITLE
Running without GPU

### ISSUE THREAD

**Issue by castelli666** [neuralchen/SimSwap#180]
Hi...first congratulation si really efficient and smart...I would like to know if there is any parameter that will allow me to use it only on CPU (no nvidia)...or a trick/emulator
Thanks a lot

**Comment by Echolink50** [comment]
I tried it. It looks for the Nvidia drivers when you run it. It may work if you manually installed in Nvidia drivers into the proper folders. I wasn't getting any GPU usage anyway so I tried it on another computer that doesn't have a GPU. It's just an i7. If you get it to run without a GPU let us know. You can also just use the Google colab.

**Comment by illtellyoulater** [comment]
According to https://github.com/neuralchen/SimSwap/issues/61 by patching the files with the script at https://pastebin.com/y1FxV8jA you can also run it without any GPU at all.

Also at the following repository https://github.com/johndpope/SimSWAP-docker you can find a dockerfile for building a Simswap docker image which if I remember correctly is already patched with the method above. 
Actually the docker image is not using the latest version of Simswap, but the penultimate one, however that's not a problem as the improvements in the latest version does not seem to produce better results (see https://github.com/neuralchen/SimSwap/issues/171).

**Comment by tikitong** [comment]
Hello, I put here the installation command lines that worked for me (MacOS Apple Chip M1). Also for CPU usage only with the Powershell script available here: https://pastebin.com/y1FxV8jA, thanks a lot for that #61, @illtellyoulater for links and #294.

Here is my configuration: `macOS-12.5.1-arm64-arm-64bit`

Assuming you have installed [brew](https://brew.sh). Hope this help. 

```yaml
brew install wget 
brew install ffmpeg
sudo softwareupdate --install-rosetta
brew install --cask powershell

conda create -n simswap python=3.9
conda activate simswap

pip install torch torchvision torchaudio    
conda install -c conda-forge protobuf numpy
pip install onnx  
pip install insightface==0.2.1 onnxruntime moviepy
pip install --ignore-installed imageio

git clone https://github.com/neuralchen/SimSwap
cd SimSwap && git pull 

wget -P ./arcface_model https://github.com/neuralchen/SimSwap/releases/download/1.0/arcface_checkpoint.tar

wget https://github.com/neuralchen/SimSwap/releases/download/1.0/checkpoints.zip

unzip ./checkpoints.zip  -d ./checkpoints

wget -P ./parsing_model/checkpoint https://github.com/neuralchen/SimSwap/releases/download/1.0/79999_iter.pth

wget --no-check-certificate "https://sh23tw.dm.files.1drv.com/y4mmGiIkNVigkSwOKDcV3nwMJulRGhbtHdkheehR5TArc52UjudUYNXAEvKCii2O5LAmzGCGK6IfleocxuDeoKxDZkNzDRSt4ZUlEt8GlSOpCXAFEkBwaZimtWGDRbpIGpb_pz9Nq5jATBQpezBS6G_UtspWTkgrXHHxhviV2nWy8APPx134zOZrUIbkSF6xnsqzs3uZ_SEX_m9Rey0ykpx9w" -O antelope.zip

unzip ./antelope.zip -d ./insightface_func/models/

pwsh patch.ps1 # FOR CPU ONLY assuming you have downloaded the file at https://pastebin.com/y1FxV8jA 

python test_video_swapsingle.py --crop_size 224 --use_mask --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path demo_file/Iron_man.jpg --video_path demo_file/multi_people_1080p.mp4 --output_path output/multi_test_swapsingle.mp4 --temp_path temp_results

------------ Options -------------
Arc_path: arcface_model/arcface_checkpoint.tar
aspect_ratio: 1.0
batchSize: 8
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
crop_size: 224
data_type: 32
dataroot: ./datasets/cityscapes/
display_winsize: 512
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: [0]
how_many: 50
id_thres: 0.03
image_size: 224
input_nc: 3
instance_feat: False
isTrain: False
label_feat: False
label_nc: 0
latent_size: 512
loadSize: 1024
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
multisepcific_dir: ./demo_file/multispecific
nThreads: 2
n_blocks_global: 6
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 3
n_local_enhancers: 1
name: people
nef: 16
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
no_instance: False
no_simswaplogo: False
norm: batch
norm_G: spectralspadesyncbatch3x3
ntest: inf
onnx: None
output_nc: 3
output_path: output/multi_test_swapsingle.mp4
phase: test
pic_a_path: demo_file/Iron_man.jpg
pic_b_path: ./crop_224/zrf.jpg
pic_specific_path: ./crop_224/zrf.jpg
resize_or_crop: scale_width
results_dir: ./results/
semantic_nc: 3
serial_batches: False
temp_path: temp_results
tf_log: False
use_dropout: False
use_encoded_image: False
use_mask: True
verbose: False
video_path: demo_file/multi_people_1080p.mp4
which_epoch: latest
-------------- End ----------------
input mean and std: 127.5 127.5
find model: ./insightface_func/models/antelope/glintr100.onnx recognition
find model: ./insightface_func/models/antelope/scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
(142, 366, 4)
  1%|▎                                          | 5/594 [00:04<09:31,  1.03it/s]  
  1%|▎      
```
